### ISSUE TITLE
Disappearing boxes

### ISSUE THREAD

**Issue by carueda** [mbari-media-management/cthulhu#20]
@hohonuuli fyi -- just entering the issue here ; )

A fragment from @[kevinsbarnard](https://github.com/kevinsbarnard) screencast demonstrating the issue:

https://user-images.githubusercontent.com/556505/165805595-6feef0e8-3be2-4bec-ac7a-e33e3e052992.mp4

**Comment by carueda** [comment]
- significant improvement with a smaller period for MediaPlayerTimer: 10ms (previously 100ms)
- boxes a more consistently being displayed (though it would be nice if we had a "move" operation that could avoid the increased flickering due to the more rapid updates)
- The mediaPlayer library (vcl4j) does not provide a consistent result when querying for the status of the media being played or paused. That is, with the media actually playing, the call `mediaPlayer.status().isPlaying()` (used by MediaPlayerTimer) switches back and forth, that is, with one true then a number of false returns in sequence, then true again and so on.

Here's how the result of an initial set of adjustments looks like:

https://user-images.githubusercontent.com/556505/165862867-19f79521-31e9-4625-843d-0f7d1319ae85.mp4

https://youtu.be/O6xiywKrubk

Hmm, but the screencast (captured using Camtasia) doesn't really seem to reflect the more frequent updates noted on Cthulhu itself.

**Comment by hohonuuli** [comment]
I've updated Cthulhu's source so it runs on M1/arm as well as amd/x86. I've been running tests on it with boxjelly and everything is working really well with the `disappearing-boxes` branch. I'm going to take this with a grain of salt as the M1's performance might be enough to hide subtle performance problems.

**Comment by carueda** [comment]
Let's then close this one per https://github.com/mbari-org/cthulhu/pull/21
