### ISSUE TITLE
The time window function for selecting and drawing bounding boxes is too coarse grained.

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/cthulhu#3]
Ideally, localization's will appear in at the frame that they are associated with.  Cthulhu allows for a user set time window, so that annotations will be drawn for longer than a single frame. Currently, the internal window function appears to only update every few seconds. This gives a very choppy display. Because the boxes are drawn before and after in time, they clutter up the screen making it hard to discern what they are drawn around. Video illustrating this is at <https://youtu.be/Rc8H5UYYodU>

**Comment by carueda** [comment]
Couple of comments/questions:

- when is the user supposed to capture a localization wrt a particular object: as soon as the object is discernible, or when the object is best visualized?
- I suppose the change in #4 should help here as the user could use a small time window, say 400ms, such that the localizations don't stay too long while playing the video.

**Comment by hohonuuli** [comment]
> when is the user supposed to capture a localization wrt a particular object: as soon as the object is discernible, or when the object is best visualized?

That's at the user's discretion. Typically (but not always) they will pause the video when drawing bounding boxes. The timestamp of the localization should be the timestamp if the mouseDown event.

> I suppose the change in #4 should help here as the user could use a small time window, say 400ms, such that the localizations don't stay too long while playing the video.

Yes, I think so too. I haven't dug into the details though.
