### ISSUE TITLE
Time window function is set as seconds. It should use milliseconds instead. 

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/cthulhu#4]
The `Time Window` user setting currenlty uses seconds. This needs to be changed to millisecs to provide for finer grained display of the localizations.

The time window defineds how long a localization is displayed (I believer the rendered time is +/- the time window. So when it's set to 1 second the localization is displayed for 2 seconds. 

This change will likely impact the underlying function which selects the annotations to be displayed.

**Comment by hohonuuli** [comment]
![Cthulhu Time Window](https://user-images.githubusercontent.com/282941/107546408-2c1d4100-6b81-11eb-96a9-318bad19bcb6.png)

**Comment by carueda** [comment]
Thanks for merging.  Closing this one (as there was no `fix #4` in any of the commits ;)
